name: CI/CD for Other Environments

on:
  push:
    branches:
      - development
      - staging
      - testing
      - uat
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Lint Source Code
        run: |
          echo "Linting code..."
          sleep 1
          echo "No lint issues found."

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Build Project
        run: |
          echo "Building the application..."
          sleep 2
          echo "Build successful!"

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Tests
        run: |
          echo "Running tests..."
          sleep 2
          echo "All tests passed!"

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Scan for Vulnerabilities
        run: |
          echo "Scanning for vulnerabilities..."
          sleep 2
          echo "No vulnerabilities found!"

  deploy:
    name: Deploy to Environment
    runs-on: ubuntu-latest
    needs: security-scan
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Deploy Application
        run: |
          echo "Deploying to environment: ${{ github.ref_name }}"
          sleep 3
          echo "Deployment to ${{ github.ref_name }} environment successful!"
